### ISSUE TITLE
Install fails on Node 14

### ISSUE THREAD

**Issue by doc-l2** [kinecosystem/kin-node#2]
It's because of the sodium-native dependency: https://github.com/sodium-friends/sodium-native/issues/136

Node 12 works. Just a heads up to update the package once that issue is fixed :)

**Comment by kikengineering** [comment]
Thanks for the heads up!

The build passed on my local machine, but as you pointed out in the issue, it's likely due the fact that I have `libtool` installed.

I _believe_ that the rest of the install / usage should still work, as `stellar-base` should fallback to `tweetnacl` if `sodium-native` is not present / built correctly.

**Comment by kikengineering** [comment]
It doesn't look like we can just 'omit' the `sodium-native` dependency, since we don't explicitly pull it in.

However, I was able to `rm -rf node_modules/sodium-native`, and everything worked correctly. A small section in https://github.com/kinecosystem/kin-node#installation has been added to highlight this.
